apiVersion: v1
kind: Service
metadata:
  name: {{ include "fdp.fullname" . }}-client
  labels:
    {{- include "fdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  type: {{ .Values.client.service.type }}
  {{- if eq .Values.client.service.clusterIP "None" }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "fdp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: client