apiVersion: v1
kind: Service
metadata:
  name: {{ include "fdp.fullname" . }}-graphdb
  labels:
    {{- include "fdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: graphdb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 7200
      targetPort: 7200
      name: http
  selector:
    {{- include "fdp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: graphdb