apiVersion: v1
kind: Service
metadata:
  name: {{ include "fdp.fullname" . }}-server
  labels:
    {{- include "fdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "fdp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server